sudo: required
services:
   - docker

before_install:
   - docker build -t w13/react-test -f ./client/Dockerfile.dev ./client
   

script:
#   - docker run -e CI=true w13/react-test npm run test
   - docker run -e CI=true w13/react-test npm run test
after_success:
   - docker build -t werton13/multi-client:v1 ./client
   - docker build -t werton13/multi-nginx:v1 ./nginx
   - docker build -t werton13/multi-server:v1 ./server
   - docker build -t werton13/multi-worker:v1 ./worker
#login to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

# take those images and push them to the DockerHub!
   - docker push werton13/multi-client:v1
   - docker push werton13/multi-nginx:v1
   - docker push werton13/multi-server:v1
   - docker push werton13/multi-worker:v1

# talk to AWS beanstalk to deploy our application

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "multi-docker"
   env: "MultiDocker-env"
# files for application in *.zip file a service name in AWSS3
# (scalable storage elasticbeanstalk-RegionName-ID - can be viewed in S3 Storage )
   bucket_name: "elasticbeanstalk-us-east-2-332194135470"
   bucket_path: "docker-multi"
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
on:
   branch: master









